"""Recommendation and report generation for the synthetic digital-twin workflow."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from hydraulic_twin.validation import ValidationResult


def recommend_actions(df: pd.DataFrame) -> list[str]:
    """Generate simple engineering-style recommendations from synthetic states."""

    recommendations: list[str] = []
    state_counts = df.get("twin_state", pd.Series(dtype=str)).value_counts()

    if state_counts.get("sensor_issue", 0) > 0:
        recommendations.append(
            "Review critical pressure and flow sensor channels before interpreting downstream metrics."
        )
    if state_counts.get("pressure_loss_suspected", 0) > 0:
        recommendations.append(
            "Inspect synthetic pressure-loss periods and compare pressure delta against command demand."
        )
    if state_counts.get("inefficient_operation", 0) > 0:
        recommendations.append(
            "Investigate high energy-use periods and check whether operating demand could be redistributed."
        )
    if state_counts.get("pump_degradation_suspected", 0) > 0:
        recommendations.append(
            "Prioritise maintenance-style review where temperature, vibration and efficiency degrade together."
        )
    if state_counts.get("load_response_anomaly", 0) > 0:
        recommendations.append(
            "Review command/load response consistency during high mismatch periods."
        )
    if state_counts.get("transient_response", 0) > 0:
        recommendations.append(
            "Inspect short transient events and compare them with operating demand changes."
        )

    if not recommendations:
        recommendations.append(
            "No major synthetic operating-state concerns were detected in this run."
        )

    recommendations.append(
        "Treat all recommendations as synthetic decision-support outputs, not operational instructions."
    )
    return recommendations


def _markdown_table(series: pd.Series, *, empty_message: str = "No entries") -> str:
    if series.empty:
        return empty_message
    lines = ["| Item | Count |", "|---|---:|"]
    for item, count in series.items():
        lines.append(f"| {item} | {int(count)} |")
    return "\n".join(lines)


def generate_report(
    df: pd.DataFrame,
    validation_result: ValidationResult,
    recommendations: list[str] | None = None,
    *,
    output_path: str | Path | None = None,
) -> str:
    """Generate a markdown report for the synthetic digital-twin pipeline."""

    recommendations = recommendations or recommend_actions(df)
    total_energy = float(df.get("cumulative_electrical_energy_kwh", pd.Series([0])).iloc[-1])
    hydraulic_energy = float(df.get("cumulative_hydraulic_energy_kwh", pd.Series([0])).iloc[-1])
    mean_efficiency = float(df.get("efficiency_estimate", pd.Series(dtype=float)).mean())
    anomaly_count = int(df.get("combined_anomaly", pd.Series(False, index=df.index)).sum())

    state_counts = df.get("twin_state", pd.Series(dtype=str)).value_counts()
    event_counts = df.get("event_label", pd.Series(dtype=str)).value_counts()

    validation_status = "PASS" if validation_result.ok else "FAIL"
    warnings = validation_result.warnings or ["No validation warnings"]
    errors = validation_result.errors or ["No validation errors"]

    report = f"""# Synthetic Hydraulic Digital Twin Report

## Publication boundary

This report is generated from fully synthetic data. It does not contain real FastBlade data, University of Edinburgh code, partner data, proprietary control logic, real facility diagrams or real operating parameters.

## Run summary

| Metric | Value |
|---|---:|
| Samples | {len(df)} |
| Validation status | {validation_status} |
| Combined anomaly samples | {anomaly_count} |
| Total electrical energy estimate [kWh] | {total_energy:.2f} |
| Total hydraulic energy estimate [kWh] | {hydraulic_energy:.2f} |
| Mean efficiency estimate | {mean_efficiency:.3f} |

## Digital-twin state counts

{_markdown_table(state_counts)}

## Synthetic event-label counts

These labels are generated by the synthetic data generator for demonstration and testing. They are not used as real operational truth.

{_markdown_table(event_counts)}

## Validation messages

### Errors

{chr(10).join(f"- {message}" for message in errors)}

### Warnings

{chr(10).join(f"- {message}" for message in warnings)}

## Recommendations

{chr(10).join(f"- {item}" for item in recommendations)}

## Notes

The current model is a baseline demonstration. It prioritises explainability, reproducibility and safe publication over hydraulic realism. Future work could add richer simulation scenarios, calibration-free uncertainty estimates, visual diagnostics and more detailed model-validation notes.
"""

    if output_path is not None:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(report, encoding="utf-8")

    return report
